name: textcast

windows:
  - service:
      layout: even-horizontal
      panes:
        - make service
  - editor:
      layout: even-horizontal
      panes:
        - nvim
  - shell:
      layout: even-horizontal
      panes:
        -
  - claude:
      layout: even-horizontal
      panes:
        - claude
  - audiobookshelf:
      layout: even-horizontal
      root: /Volumes/Storage/Data/AudioBookShelf
      panes:
        -
