name: textcast

windows:
  - editor:
      layout: even-horizontal
      panes:
        - nvim
  - shell:
      layout: even-horizontal
      panes:
        -
  - claude:
      layout: even-horizontal
      panes:
        - claude
