name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install ffmpeg on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install ffmpeg on macOS
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg
      - name: Install dependencies
        run: |
          pip install '.[test]'
      - name: Install playwright chromium browser
        run: |
          playwright install chromium
      - name: Run tests
        run: |
          pytest -v
          cog --check README.md

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine build
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build
          twine upload dist/*
